Feature/second page/style
luanaggoncalves/technicalshare.frontend pull request #4
Opened 2022-04-08 17:54 UTC by JessMotta

I added styling on page two (show mentor info) and added some css files modulating sections in HTML.

2022-04-09 20:28 UTC, JessMotta commented
I changed content's  width in screens larger than 1024px and font size.

2022-04-10 17:53 UTC, luanaggoncalves requested changes

2022-04-10 17:53 UTC, luanaggoncalves commented on scripts/calendar.js
> +      "FeV",
```suggestion
      "Fev",
```

2022-04-10 18:14 UTC, JessMotta commented on scripts/calendar.js
> +      "FeV",
fixed

2022-04-10 23:21 UTC, luanaggoncalves approved these changes
Approved

2022-04-10 23:56 UTC, jotape-SL approved these changes

2022-04-11 00:38 UTC, merged